import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>01-exercicios</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ol
          style={{
            fontSize: "20px",
            lineHeight: "30px",
            margin: "20px 0 0 40px",
            listStyle: "number",
          }}
        >
          <li>
            <Link href="/basicos/primeiro">Primeiro</Link>
          </li>
          <li>
            <Link href="/basicos/jsx01">JSX 01</Link>
          </li>
          <li>
            <Link href="/basicos/jsx02">JSX 02</Link>
          </li>
          <li>
            <Link href="/basicos/jsx03">JSX 03</Link>
          </li>
          <li>
            <Link href="/basicos/jsx04">JSX 04</Link>
          </li>
          <li>
            <Link href="/basicos/lista01">Lista 01</Link>
          </li>
          <li>
            <Link href="/basicos/fragment01">Fragmento 01</Link>
          </li>
          <li>
            <Link href="/basicos/usando-titulo">Usando Componente</Link>
          </li>
          <li>
            <Link href="/basicos/estilos/integracao01">Integração CSS 01</Link>
          </li>
          <li>
            <Link href="/basicos/estilos/integracao02">Integração CSS 02</Link>
          </li>
          <li>
            <Link href="/basicos/estilos/usando-estilos">Aplicando Estilo CSS</Link>
          </li>
          <li>
            <Link href="/basicos/estilos/usando-estilos">Aplicando Estilo CSS</Link>
          </li>
          <li>
            <Link href="/render/repeticao01">Repetição 01</Link>
          </li>
          <li>
            <Link href="/render/condicional01">Condicional 01</Link>
          </li>
          <li>
            <Link href="/render/condicional02">Condicional 02</Link>
          </li>
          <li>
            <Link href="/basicos/componente-com-filho">Componente com Filho</Link>
          </li>
          <li>
            <Link href="/comunicacao/direta">Comunicação Direta</Link>
          </li>
          <li>
            <Link href="/basicos/botao">Eventos JS</Link>
          </li>
          <li>
            <Link href="/comunicacao/indireta01">Comunicação Indireta 01</Link>
          </li>
          <li>
            <Link href="/estado/mouse">Estado - Mouse</Link>
          </li>
          <li>
            <Link href="/estado/contador">Estado - Contador</Link>
          </li>
          <li>
            <Link href="/estado/formulario">Componente Controlado</Link>
          </li>
          <li>
            <Link href="/estado/mega-sena">Mega Sena</Link>
          </li>
          <li>
            <Link href="/ts/exemplo">Exemplo TS</Link>
          </li>
        </ol>
      </main>
    </div>
  );
}
