import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const lista = [
  ["/rotas/123/buscar", "Rota dinâmica 1"],
  ["/rotas/olhe-a-url/é-rota-dinamica", "Rota dinâmica 2"],
  ["/rotas/params?nome=helton&idade=25", "Usando parâmetros"],
];

export default () => (
  <div className={styles.container}>
    <Head>
      <title>02-next-basico</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <ol
        style={{
          fontSize: "20px",
          margin: "20px 0 0 40px",
          listStyle: "circle",
        }}
      >
        {lista.map((e, i) => (
          <li key={i}>
            <Link href={e[0]}>{e[1]}</Link>
          </li>
        ))}
      </ol>
    </main>
  </div>
);
