import Head from "next/head";
import Link from "next/link";
import router from "next/router";
import styles from "../styles/Home.module.css";

const lista = [
  ["/rotas/123/buscar", "Rota dinâmica 1"],
  ["/rotas/olhe-a-url/é-rota-dinamica", "Rota dinâmica 2"],
  ["/rotas/params?nome=helton&idade=25", "Usando parâmetros"],
  ["/api/hello", "API padrão do next"],
  ["/api/metodo", "API teste 1 (usar rest client)"],
  ["/questao", "API teste 2"],
  ["/form", "Integração com API"],
  ["/api/params1/é/possivel/passar/n/parâmetros", "API com múltiplos parâmetros"],
  ["/api/params2/", "API com parâmetros opcionais (não recebe 404)"],
  ["/asd123", "Alteração da página 404"],
  ["/nao-estatica", "Renderização NÃO Estática"],
  ["/estatica", "Renderização Estática"],
];

export default function Index() {
  return (
    <div className={styles.container}>
      <Head>
        <title>03-next-basico</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ol
          style={{
            fontSize: "20px",
            lineHeight: "30px",
            margin: "20px 0 0 40px",
            listStyle: "number",
          }}
        >
          {lista.map(([url, titulo], i) => (
            <li key={i}>
              <Link href={url}>{titulo}</Link>
            </li>
          ))}
          <li>
            <button onClick={() => router.push("/rotas/programatico?nome=Helton")}>
              Roteamento programático 1
            </button>
          </li>
          <li>
            <button
              onClick={() =>
                router.push({
                  pathname: "/rotas/programatico",
                  query: { id: "13", nome: "Helton" },
                })
              }
            >
              Roteamento programático 2
            </button>
          </li>
        </ol>
      </main>
    </div>
  );
}
